-- src/test/resources/schema.sql
-- Minimal H2-compatible schema adapted from your Postgres dump
-- Use BIGINT for ids, INTEGER for status/type fields to match Java Integer

CREATE TABLE IF NOT EXISTS "user"
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    useraccount   VARCHAR(50),
    username      VARCHAR(50),
    userpwd       VARCHAR(100),
    useravatar    VARCHAR(255),
    useremail     VARCHAR(50),
    userrole      INTEGER,
    islogin       BOOLEAN,
    isword        BOOLEAN,
    lastlogintime TIMESTAMP,
    createtime    TIMESTAMP
);

CREATE TABLE IF NOT EXISTS category
(
    id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(255),
    isuse BOOLEAN
);

CREATE TABLE IF NOT EXISTS product
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(255),
    detail     CLOB,
    coverlist  CLOB,
    oldlevel   INTEGER,
    categoryid BIGINT,
    userid     BIGINT,
    inventory  INTEGER,
    price      DECIMAL(12, 2),
    isbargain  BOOLEAN,
    createtime TIMESTAMP
);

CREATE TABLE IF NOT EXISTS address
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid        BIGINT,
    contactperson VARCHAR(255),
    addressdetail VARCHAR(255),
    contactphone  VARCHAR(255),
    isdefault     BOOLEAN
);

CREATE TABLE IF NOT EXISTS interaction
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid     BIGINT,
    productid  BIGINT,
    type       INTEGER,
    createtime TIMESTAMP
);

CREATE TABLE IF NOT EXISTS content
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid     BIGINT,
    name       VARCHAR(255),
    detail     CLOB,
    cover      VARCHAR(255),
    createtime TIMESTAMP
);

CREATE TABLE IF NOT EXISTS evaluations
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    parentid    BIGINT,
    commenterid BIGINT,
    replierid   BIGINT,
    contenttype VARCHAR(100),
    contentid   BIGINT,
    content     VARCHAR(255),
    createtime  TIMESTAMP
);

CREATE TABLE IF NOT EXISTS evaluationsupvote
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid        BIGINT,
    evaluationsid BIGINT
);

CREATE TABLE IF NOT EXISTS message
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid     BIGINT,
    content    VARCHAR(255),
    isread     BOOLEAN,
    createtime TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operationlog
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid     BIGINT,
    detail     VARCHAR(255),
    createtime TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(255),
    detail          VARCHAR(255),
    userid          BIGINT,
    productid       BIGINT,
    buyprice        DECIMAL(12, 2),
    buynumber       INTEGER,
    tradestatus     INTEGER,
    tradetime       TIMESTAMP,
    refundstatus    INTEGER,
    refundtime      TIMESTAMP,
    isrefundconfirm BOOLEAN,
    isconfirmtime   TIMESTAMP,
    isconfirm       BOOLEAN,
    addressid       BIGINT,
    isdeliver       BOOLEAN,
    delivertime     TIMESTAMP,
    deliveradrid    BIGINT,
    createtime      TIMESTAMP
);

-- Indexes (optional but kept similar to original)
CREATE INDEX IF NOT EXISTS idx_address_userid ON address (userid);
CREATE INDEX IF NOT EXISTS idx_content_userid ON content (userid);
CREATE INDEX IF NOT EXISTS idx_evaluations_commenterid ON evaluations (commenterid);
CREATE INDEX IF NOT EXISTS idx_evaluations_parentid ON evaluations (parentid);
CREATE INDEX IF NOT EXISTS idx_evaluations_replierid ON evaluations (replierid);
CREATE INDEX IF NOT EXISTS idx_evaluationsupvote_evaluationsid ON evaluationsupvote (evaluationsid);
CREATE INDEX IF NOT EXISTS idx_evaluationsupvote_userid ON evaluationsupvote (userid);
CREATE INDEX IF NOT EXISTS idx_interaction_productid ON interaction (productid);
CREATE INDEX IF NOT EXISTS idx_interaction_userid ON interaction (userid);
CREATE INDEX IF NOT EXISTS idx_message_userid ON message (userid);
CREATE INDEX IF NOT EXISTS idx_operationlog_userid ON operationlog (userid);
CREATE INDEX IF NOT EXISTS idx_orders_addressid ON orders (addressid);
CREATE INDEX IF NOT EXISTS idx_orders_deliveradrid ON orders (deliveradrid);
CREATE INDEX IF NOT EXISTS idx_orders_productid ON orders (productid);
CREATE INDEX IF NOT EXISTS idx_orders_userid ON orders (userid);
CREATE INDEX IF NOT EXISTS idx_product_categoryid ON product (categoryid);
CREATE INDEX IF NOT EXISTS idx_product_userid ON product (userid);

-- Foreign keys (H2 will enforce these)
ALTER TABLE address
    ADD CONSTRAINT fk_address_user FOREIGN KEY (userid) REFERENCES "user" (id);
ALTER TABLE content
    ADD CONSTRAINT fk_content_user FOREIGN KEY (userid) REFERENCES "user" (id);
ALTER TABLE evaluations
    ADD CONSTRAINT fk_evaluations_commenter FOREIGN KEY (commenterid) REFERENCES "user" (id);
ALTER TABLE evaluations
    ADD CONSTRAINT fk_evaluations_parent FOREIGN KEY (parentid) REFERENCES evaluations (id);
ALTER TABLE evaluations
    ADD CONSTRAINT fk_evaluations_replier FOREIGN KEY (replierid) REFERENCES "user" (id);
ALTER TABLE evaluationsupvote
    ADD CONSTRAINT fk_evaluationsupvote_evaluation FOREIGN KEY (evaluationsid) REFERENCES evaluations (id);
ALTER TABLE evaluationsupvote
    ADD CONSTRAINT fk_evaluationsupvote_user FOREIGN KEY (userid) REFERENCES "user" (id);
ALTER TABLE interaction
    ADD CONSTRAINT fk_interaction_product FOREIGN KEY (productid) REFERENCES product (id);
ALTER TABLE interaction
    ADD CONSTRAINT fk_interaction_user FOREIGN KEY (userid) REFERENCES "user" (id);
ALTER TABLE message
    ADD CONSTRAINT fk_message_user FOREIGN KEY (userid) REFERENCES "user" (id);
ALTER TABLE operationlog
    ADD CONSTRAINT fk_operationlog_user FOREIGN KEY (userid) REFERENCES "user" (id);
ALTER TABLE orders
    ADD CONSTRAINT fk_orders_address FOREIGN KEY (addressid) REFERENCES address (id);
ALTER TABLE orders
    ADD CONSTRAINT fk_orders_deliver_address FOREIGN KEY (deliveradrid) REFERENCES address (id);
ALTER TABLE orders
    ADD CONSTRAINT fk_orders_product FOREIGN KEY (productid) REFERENCES product (id);
ALTER TABLE orders
    ADD CONSTRAINT fk_orders_user FOREIGN KEY (userid) REFERENCES "user" (id);
ALTER TABLE product
    ADD CONSTRAINT fk_product_category FOREIGN KEY (categoryid) REFERENCES category (id);
ALTER TABLE product
    ADD CONSTRAINT fk_product_user FOREIGN KEY (userid) REFERENCES "user" (id);
